name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker run
      run: docker run jradik/async-cache-warmer -s "https://acmotos.com/es/module/lgsitemaps/sitemap?name=category_1_1" -s "https://acmotos.com/es/module/lgsitemaps/sitemap?name=product_1_1" -l 2
